### ISSUE TITLE
how to use

### ISSUE THREAD

**Issue by ghost** [mjasny/wp-nuliga#1]
Hello,
i've found this wp-plugin. And i am very happy that you develop this for Wordpress.
But i'am in trouble to use it.
I do this:
1. Upload `nuliga.php` to the `/wp-content/plugins/` directory                -> Done
1. Activate the plugin through the 'Plugins' menu in WordPress              -> Done
1. Place `<?php do_action('plugin_name_hook'); ?>` in your templates    -> not done
because i don't know what you mean with this.....

#Till now i uses the SiS-Handball plugin. But now i have to use nuliga to get my Data.

P.S.: If you speak german, it is easier for me to answer in german. Thanks

**Comment by mjasny** [comment]
Gude,

geht viel einfacher, die Instruktionen waren noch von woanders übrig geblieben :)

Einfach das Repository als ZIP Archiv herunterladen (https://github.com/mjasny/wp-nuliga/archive/master.zip)
Dann bei Wordpress auf Plugin > Plugin hochladen > Plugin aktivieren.

Vielleicht lade ich das Plugin irgendwann bei Wordpress hoch, dann gibt es auch automatische Updates....

Jetzt kannst du irgendwo auf dem Blog mit folgenden HTML Elementen arbeiten (es gibt noch mehr: https://harald-herberth.github.io/nuTab/) 

(Parameter überall anpassen, findest du auf Nuliga unter deinem Verein)

`<div class="srsPlanVerein" srsverband="hhv-handball" srsclub="blablabla" srsohnehalle="1"></div>`

`<div class="srsTab" srsurl="https://hhv-handball.liga.nu/cgi-bin/WebObjects/nuLigaHBDE.woa/wa/groupPage?championship=blablabla;group=blablabla" srsverein="blablabla" srsauchspiele="1"></div>`

`<div class="srsPlan" srsurl="https://hhv-handball.liga.nu/cgi-bin/WebObjects/nuLigaHBDE.woa/wa/groupPage?championship=blablabla;group=blablabla" srsverein="blablabla"></div>`

**Comment by ghost** [comment]
Vielen Dank. Damit bin ich schon ein gutes Stück weiter gekommen.

Du weißt aber nicht zufällig, ob man die Hallennummern automatisch zu echten Namen umbenennen kann, oder wenigstens wie auf der nuliga seite anzeigen lassen kann wenn man mit der Maus drüber fährt....

**Comment by mjasny** [comment]
Ja, das geht aber nuTab unterstützt dies nicht, deswegen habe ich sie bei mir auch ausgeblendet.

Das was bei nuliga angezeigt wird, wenn du mit der Maus drüber fährst, kommt von dem alt/title attribute des span Elements. Es sollte ganz einfach sein das bei nuTab einzubauen.

Habe noch ein Skript um alle Spiele in einen Kalender zu packen und da mache ich es mit:
```python
def get_halle(url):
    page = requests.get(url)
    document = html.fromstring(page.text)
    link = document.xpath('//a[contains(text(),"Routenplaner...")]/@href')[0]
    
    m = re.search(r'tocity=(?P<city>[^&]+)&toplz=(?P<plz>[^&]+)&tostreet=(?P<street>[^&]+)&tocountry=(?P<country>[^&]+)', link)
    return '{street}, {plz} {city}'.format(**m.groupdict())
```
