### ISSUE TITLE
Error in GET srsTab: error

### ISSUE THREAD

**Issue by daniel94ger** [mjasny/wp-nuliga#2]
Moin,

hatte mich sehr gefreut, als ich dieses Plugin für Wordpress gefunden habe, weil ich die manuelle Installation von nutab einfach nicht auf die Reihe bekommen habe. Leider kommt folgende Fehlermeldung, wenn ich auf einer Seite mittels <div>...</div> den link einsetze: Error in GET srsTab: error

Die Seite mit dem Problem ist folgende: https://tennis.sc-uckerath.de/team/herren-2/

Als Code über den Texteditor hab ich folgendes eingegeben: `<div class="srsTab" srsurl="https://tvm.liga.nu/cgi-bin/WebObjects/nuLigaTENDE.woa/wa/teamPortrait?team=2603238&amp;championship=RRH+S+2021"></div>`

Würde mich sehr freuen, wenn es irgendeine Lösung für mein problem geben würde.

Lg Daniel

**Comment by daniel94ger** [comment]
`<div class="srsTab" srsurl="https://tvm.liga.nu/cgi-bin/WebObjects/nuLigaTENDE.woa/wa/teamPortrait?team=2603238&amp;championship=RRH+S+2021"></div>
`

der versprochene code:D

**Comment by mjasny** [comment]
Gude,

was war jetzt dein Fehler?
