### ISSUE TITLE
Hallenübericht

### ISSUE THREAD

**Issue by maxvh3688** [mjasny/wp-nuliga#5]
@mjasny Kannst du mir sagen ob und wenn ja wie es möglich ist eine Extra Tabelle mit den Hallen und den Adressen zu erstellen?

Grüße

Max

**Comment by mjasny** [comment]
Hallo Max,

ich habe gesehen, dass du die gleiche Frage schon bei https://github.com/harald-herberth/nutab/ erstellt hast.
Ich persönlich habe so eine Funktion noch nicht genutzt, aber sowas könnte eigentlich sehr nützlich sein.
Ich glaube Harald bei nutab wird da mehr wissen können, da er das eigentliche Plugin programmiert hat. Das wp-nuliga bindet eigentlich nur seinen Code bequem als wordpress-plugin ein und kann auch nur das was das normale nutab kann.

Beste Grüße,
Matthias
